//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INFO_JIG
    {
        public int IDJIG { get; set; }
        public string QRCODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string PARTNUMBER { get; set; }
        public string RANK { get; set; }
        public string FIXED_ASSET_NO { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> BALANCE { get; set; }
        public byte[] PICTURE { get; set; }
        public string PO_RQ { get; set; }
        public string QUOTATION { get; set; }
        public string REMARK { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> IDSTAFF { get; set; }
        public string IDCUSTOMER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
