//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INFO_FMA_EXPLAIN
    {
        public int IDEXPLAIN { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string REMARK { get; set; }
    }
}
