//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INFO_FMA_INDETAIL
    {
        public int IDINDETAIL { get; set; }
        public int IDFMA { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<int> QTY { get; set; }
        public string QTY_UNIT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string LOCATION_SHELFNO { get; set; }
        public string BOXNO { get; set; }
        public string FMVTJ_CODE { get; set; }
        public string RACK { get; set; }
        public string REMARK { get; set; }
    }
}
