//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REP_MONTHLY
    {
        public int IDMONTHLY { get; set; }
        public string IDCUSTOMER { get; set; }
        public int IDSTAFF { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DAY { get; set; }
        public Nullable<System.TimeSpan> CHECKIN { get; set; }
        public Nullable<System.TimeSpan> CHECKOUT { get; set; }
        public Nullable<int> IDMCTYPE { get; set; }
        public string LINE_NO { get; set; }
        public Nullable<System.DateTime> INSTALLATION_DATE { get; set; }
        public string ACTIVITY { get; set; }
        public Nullable<int> TRANSPORT { get; set; }
        public string SRNO { get; set; }
        public string NATURE { get; set; }
        public Nullable<decimal> CHARGEABLE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
    }
}
