//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_INFO_FMV_STK
    {
        public int IDFMVSTK { get; set; }
        public string MCTYPE { get; set; }
        public string STATUS { get; set; }
        public string PARTNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string SERIALNO { get; set; }
        public string RATING { get; set; }
        public Nullable<int> BALANCE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> QTY { get; set; }
        public string QTY_UNIT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string LOCATION_SHELFNO { get; set; }
        public string BOXNO { get; set; }
        public string FMVTJ_CODE { get; set; }
        public string RACK { get; set; }
        public string IN_REMARK { get; set; }
        public Nullable<int> OUT_QTY { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public string OUT_RACK { get; set; }
        public string HISTORY { get; set; }
        public string OUT_REMARK { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<bool> READY { get; set; }
        public string QRCODE { get; set; }
    }
}
