//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_COM_CUSTOMER> T_COM_CUSTOMER { get; set; }
        public virtual DbSet<T_COM_SEQUENCE> T_COM_SEQUENCE { get; set; }
        public virtual DbSet<T_COM_STAFF> T_COM_STAFF { get; set; }
        public virtual DbSet<T_SLOGAN> T_SLOGAN { get; set; }
        public virtual DbSet<T_SYS_FUNC> T_SYS_FUNC { get; set; }
        public virtual DbSet<T_SYS_GROUP> T_SYS_GROUP { get; set; }
        public virtual DbSet<T_SYS_RIGHT> T_SYS_RIGHT { get; set; }
        public virtual DbSet<T_SYS_USER> T_SYS_USER { get; set; }
        public virtual DbSet<T_HIS_PARTIN> T_HIS_PARTIN { get; set; }
        public virtual DbSet<T_HIS_PARTOUT> T_HIS_PARTOUT { get; set; }
        public virtual DbSet<View_HIS_PARTOUT> View_HIS_PARTOUT { get; set; }
        public virtual DbSet<View_HIS_PARTIN> View_HIS_PARTIN { get; set; }
        public virtual DbSet<T_INFO_JIG> T_INFO_JIG { get; set; }
        public virtual DbSet<T_INFO_PART> T_INFO_PART { get; set; }
    }
}
