//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMV_SYSTEM_MANAGEMENTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COM_STAFF
    {
        public int IDSTAFF { get; set; }
        public string STAFFNAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string POSITION { get; set; }
        public string CCCD { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
    }
}
